name: "📖 Documentation"
description: "A catch-all template for issues about documentation"

title: "[Docs]: "
labels: documentation

body:
  - type: textarea
    attributes:
      label: Summary and description
      description: >
        The body of the issue, just like a regular GitHub issue.
        The more detail you provide, the better,
        but try to start with a summary to frame the issue.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Are you interested in working on this?
      description: >
        No pressure—this is totally optional!
        We just want to invite you to contribute.
        If you choose to contribute, the core team will be there to help you the whole way.


        If this issue is triaged as lower priority,
        your willing and ableness to work on it will land it faster than waiting for one of us to pick it up.
      options:
        - label: I'm interested in working on this
