name: "💬 RFC"
description: "For detailed proposals about new features or changes to existing ones"

title: "[RFC]: "
labels: enhancement

body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to open an RFC!
        Please note that this is for detailed proposals.
        If you have a feature request, or would like to brainstorm,
        the discussions section of this repo is a better place to start.

  - type: textarea
    attributes:
      label: Summary
      description: >
        Start with a summary to frame the proposal.
        Including a code example upfront goes a long way.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Motivation
      description: >
        Here your goal is to answer the question "Why are we doing this?"
        As put by other RFC templates,
        "enumerate the constraints you're trying to solve
        without coupling them too closely to the solution you have in mind."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Detailed proposal
      description: |
        Write your proposal here. You're welcome to structure it however you like, but the more detail, the better. Get into the specifics and include examples. Keep this non-exhaustive list of questions in mind as you write:

        - What's this about?
        - What's the design in detail?
        - Is this a breaking change? How easy will it be for current users to adopt?
        - What parts of the design are still TBD?
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Are you interested in working on this?
      description: >
        No pressure—this is totally optional!
        We just want to invite you to contribute to Redwood.
        If you choose to contribute, the core team will be there to help you the whole way.


        If this issue is triaged as lower priority,
        your willing and ableness to work on it will land it faster than waiting for one of us to pick it up.
      options:
        - label: I'm interested in working on this
